trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration : 'production' 

steps:
- script: |
    npm install
    npm run build
  displayName: 'Install Dependencies and Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/dist'
    ArtifactName: 'golaphazarika-app'
  displayName: 'Publish Build Artifacts'


