trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

# Install dependencies
- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install Dependencies'

# Lint the Angular project
- script: |
    ng lint
  displayName: 'Lint Angular Project'

# Build the Angular project
- script: |
    ng build --prod
  displayName: 'Build Angular Project'

